name: RedisTrade
version: '${version}'
main: dev.unnm3d.redistrade.RedisTrade
api-version: '1.19'
depend:
  - Vault
libraries:
  - net.kyori:adventure-text-minimessage:4.17.0
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.46.0.0
  - io.lettuce:lettuce-core:6.4.0.RELEASE
permissions:
  redistrade.trade:
    description: Open the trade GUI
    default: true
  redistrade.ignore:
    description: Ignore a trade
    default: true
  redistrade.browse:
    description: Browse the trades
    default: op
  redistrade.setitem:
    description: Set a gui item from your hand
    default: op
  redistrade.getitem:
    description: Get a gui item to your hand
    default: op
  redistrade.stresser:
    description: Stress test the plugin
    default: op
  redistrade.usecurrency.default:
    description: Use the default currency
    default: true
  redistrade.admin:
    description: Use the default currency
    default: op
    children:
      redistrade.browse: true
      redistrade.setitem: true
      redistrade.getitem: true
      redistrade.stresser: true